// Generated by ReScript, PLEASE EDIT WITH CARE


function reducer(stateOpt, action) {
  var state = stateOpt !== undefined ? stateOpt : 1;
  var $$int = action.type;
  if (typeof $$int === "number") {
    if ($$int !== 0) {
      return state - 1 | 0;
    } else {
      return state + 1 | 0;
    }
  } else {
    return $$int._0;
  }
}

export {
  reducer ,
  
}
/* No side effect */
