// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ReactRedux from "react-redux";

function Test(Props) {
  var state = ReactRedux.useSelector(function (store) {
        return store;
      });
  var dispatch = ReactRedux.useDispatch();
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, "Hello World"), React.createElement("div", undefined, state), React.createElement("button", {
                  title: "increment",
                  onClick: (function (param) {
                      return Curry._1(dispatch, {
                                  type: /* Decrement */1
                                });
                    })
                }, "Decrement"), React.createElement("button", {
                  title: "increment",
                  onClick: (function (param) {
                      return Curry._1(dispatch, {
                                  type: /* Increment */0
                                });
                    })
                }, "increment"));
}

var make = Test;

export {
  make ,
  
}
/* react Not a pure module */
